name: Validate filenames

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_files
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}/files
          owner: DevCraft-Academy
          repo: exercises
          pull_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint Filenames
        uses: kurnev/match-against-glob-action@v1
        with:
          filenames: ${{ join(fromJson(steps.get_files.outputs.data).*.filename) }}
          patterns: './**/^((?![\\\/:*?\"<>|]).)*$'
